hugging_face:
  base_url: "https://api-inference.huggingface.co/models"
  model_id: "gpt2"
  parameters:
    max_new_tokens: 50
    num_return_sequences: 1
    temperature: 0.8
api_client:
  retry:
    max_retries: 3
    status_forcelist: [500, 502, 503, 504]
    backoff_factor: 0.5
